usage: Resource type for API operations on collection of resources
description: A collection of <<resourcePathName>> in the system. Due to the high volume of data that can be retrieved, the response is paginated.

get:
  is: [throwsForbiddenError,throwsResourceNotFoundError,throwsInternalServerError]
  description: Retrieve all <<resourcePathName | !pluralize>>
  headers:
    If-Modified-Since:
      description: Timestamp when the collection was last modified.
      required: false
  responses:
    200:
      description: Success response.
      headers:
        Last-Modified:
          description: The date this collection was last modified (resource added, removed or updated)
          example: "Wed, 15 Jun 2018 15:00:00"
          required: true
      body:
        application/json:
          example: <<examplePaginatedResponseExample>>
          type: <<examplePaginatedResponseType>>



post:
  is: [throwsForbiddenError,throwsInternalServerError]
  description: Create a new instance of <<resourcePathName | !singularize>>
  body:
    application/json:
      example: <<createResourceRequestExample>>
      type: <<createResourceRequestType>>

  responses:
    201:
      description: Succesfully created a new <<resourcePathName | !singularize>>
      headers:
        Content-Location:
          description: Location of the newly created <<resourcePathName | !singularize>>
          type: string
          required: false
      body:
        application/json:
          description: Returns the created <<resourcePathName | !singularize>> resource
          example: <<createResourceResponseExample>>
          type: <<createResourceResponseType>>

    400:
      description: Invalid API request submitted for creating a new <<resourcePathName | !singularize>>
      body:
        application/json:
          example: <<createResourceBadRequestExample>>
          type: errorResponse
