description: Trait for paginated requests, setting the page number and/or size parameters
queryParameters:
  pageNo:
    description: The page number to fetch
    type: number
    required: false
    default: 0
    example: 5
  pageSize:
    description: The maximum number of records to fetch per page
    type: number
    required: false
    default: 100
    example: 5
