description: Trait for sortable requests, setting the sorting field and order
queryParameters:
  sortBy:
    description: |
      List of fields to sort by (comma separated). For example: #TODO: add example
    type: string
    required: false
    example: -firstName,lastName
