description: Resource not found exception
responses:
  404:
    description: Resource not found
    body:
      application/json:
        example: !include ../examples/404-resoureNotFound-example.json
