description: |
  API throws HTTP 404 - resource not found exception if the resource cannot be located in the URI
responses:
  404:
    body:
      application/json:
        example: !include ../examples/404-resoureNotFound-example.json
